### ISSUE TITLE
WIFI driver installation not working

### ISSUE THREAD

**Issue by erytw** [vrolife/modern_laptop#20]
installing wifi driver gives this error:
![изображение](https://user-images.githubusercontent.com/71668578/188276924-58577a7e-f51c-4c50-b3f3-a0439993ad2f.png)
kernel 5.19.6-arch1-1
log:
[make.log](https://github.com/vrolife/modern_laptop/files/9482892/make.log)

**Comment by vrolife** [comment]
fixed https://github.com/vrolife/modern_laptop/commit/72fa4327b32469600cdf5455f5c1ae29885bc260

**Comment by erytw** [comment]
> fixed [72fa432](https://github.com/vrolife/modern_laptop/commit/72fa4327b32469600cdf5455f5c1ae29885bc260)
still getting this problem
[make.log](https://github.com/vrolife/modern_laptop/files/9483032/make.log)

![изображение](https://user-images.githubusercontent.com/71668578/188280958-d0688e72-0c10-4b16-b5ae-f66357ef80fe.png)

**Comment by vrolife** [comment]
Sorry, I forgot to change the version number.
. https://github.com/vrolife/modern_laptop/commit/879c2863f9c7d233e24a10db62976514a3026ad5

**Comment by erytw** [comment]
Thanks! Now it works.
